/**
 * Phase 5 plan 05-04 Task 2: CMD-10 /gsd-import integration test.
 *
 * Exercises the `/gsd-import` brownfield-command path: start from a bare
 * jj-colocated tmpdir (NO synth skeleton — this is the empty-fresh-import
 * path), simulate the import workflow by writing the four top-level
 * `.planning/` files, then commit the result. Verifies the ROADMAP /
 * REQUIREMENTS / STATE / PROJECT skeleton-creation path works on jj.
 *
 * D-34 coverage gap: brownfield commands exercised against synthetic jj
 * fixtures only; full dogfood validation occurs in Phase 6 once the
 * sticky-adapter flip + `.planning/` SHA → change_id rewriter exist.
 *
 * Suite skips when `jj --version` is unavailable.
 */

import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdirSync, mkdtempSync, rmSync, writeFileSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { execSync } from 'node:child_process';
import { createVcsAdapter } from '../index.js';
import type { JjVcsAdapter } from '../types.js';

let jjAvailable = false;
try {
	execSync('jj --version', { stdio: 'pipe' });
	jjAvailable = true;
} catch {
	// jj not on PATH; entire suite skips.
}

// Local init helper — this file deliberately does NOT use synthPlanningFixture
// because /gsd-import operates on a repo that does NOT yet have a `.planning/`
// skeleton. The skeleton is the workflow's OUTPUT, not its input.
function initEmptyJjColocated(): string {
	// Unique tmpdir prefix per CMD-* file (pre-empts Phase 4 LEARNINGS
	// tmpdir-contention flake category; will be re-validated by plan 05-05).
	const dir = mkdtempSync(join(tmpdir(), 'gsd-cmd-import-jj-'));
	execSync('jj git init --colocate', { cwd: dir, stdio: 'pipe' });
	execSync('jj config set --repo user.email "test@test.com"', {
		cwd: dir,
		stdio: 'pipe',
	});
	execSync('jj config set --repo user.name "Test"', {
		cwd: dir,
		stdio: 'pipe',
	});
	return dir;
}

describe.skipIf(!jjAvailable)(
	'CMD-10 (/gsd-import) — jj-colocated bare-tmpdir (D-34)',
	() => {
		let dir: string;
		let vcs: JjVcsAdapter;

		beforeEach(() => {
			dir = initEmptyJjColocated();
			vcs = createVcsAdapter(dir, { kind: 'jj' }) as JjVcsAdapter;
		});

		afterEach(() => {
			if (dir) rmSync(dir, { recursive: true, force: true });
		});

		it('Test 1: ROADMAP / REQUIREMENTS / STATE / PROJECT skeleton emerges from import flow', () => {
			// Pre: bare tmpdir has no .planning/.
			expect(existsSync(join(dir, '.planning'))).toBe(false);

			// Simulate the import workflow writing the four top-level files.
			mkdirSync(join(dir, '.planning'), { recursive: true });
			writeFileSync(
				join(dir, '.planning/PROJECT.md'),
				'# Imported Project\n\nGenerated by /gsd-import.\n',
			);
			writeFileSync(
				join(dir, '.planning/REQUIREMENTS.md'),
				'# Requirements\n\n- IMPORT-01 ...\n',
			);
			writeFileSync(
				join(dir, '.planning/ROADMAP.md'),
				'# Roadmap\n\n- [ ] Phase 1\n',
			);
			writeFileSync(
				join(dir, '.planning/STATE.md'),
				'---\nmilestone: v0.1\n---\n\n# State\n',
			);

			// Post: all four exist.
			expect(existsSync(join(dir, '.planning/PROJECT.md'))).toBe(true);
			expect(existsSync(join(dir, '.planning/REQUIREMENTS.md'))).toBe(true);
			expect(existsSync(join(dir, '.planning/ROADMAP.md'))).toBe(true);
			expect(existsSync(join(dir, '.planning/STATE.md'))).toBe(true);
		});

		it('Test 2: commits the import via vcs.commit({files: [...4 files]}) — appears in log', () => {
			mkdirSync(join(dir, '.planning'), { recursive: true });
			writeFileSync(join(dir, '.planning/PROJECT.md'), '# P\n');
			writeFileSync(join(dir, '.planning/REQUIREMENTS.md'), '# R\n');
			writeFileSync(join(dir, '.planning/ROADMAP.md'), '# M\n');
			writeFileSync(join(dir, '.planning/STATE.md'), '# S\n');

			const r = vcs.commit({
				message: 'chore: import project from inputs',
				files: [
					'.planning/PROJECT.md',
					'.planning/REQUIREMENTS.md',
					'.planning/ROADMAP.md',
					'.planning/STATE.md',
				],
			});
			expect(r.exitCode).toBe(0);
			expect(r.hash).toBeTruthy();

			// jj squash-based commit lands the message on @-'s description (jj
			// squash -B @ -k -m); head @ is a fresh empty commit. Query the
			// ancestry chain rather than the head entry — same shape as
			// cmd-discuss-phase-jj.test.ts.
			const log = vcs.log({ maxCount: 10, allRefs: true });
			expect(log.length).toBeGreaterThan(0);
			const subjects = log.map((e) => e.subject).join(' | ');
			expect(subjects).toContain('chore: import project from inputs');
		});
	},
);
