/**
 * format-migration/report.ts — markdown emitter for the migration report.
 *
 * Output path: `<cwd>/.planning/intel/06-migration-report.md` (CONTEXT D-01;
 * RESEARCH §"Sample report row shape").
 *
 * Shape: two tables — ancestor-resolved orphans (with optional jj children
 * column) and unresolvable orphans. Empty tables render an explicit `_(none)_`
 * placeholder row so the file is well-formed even on a clean migration.
 *
 * The report is itself an INTEL surface, not a STATE-of-the-world surface;
 * it is NOT re-scanned by subsequent migrations (it describes WHAT was
 * migrated, not user content). Documented in 06-02-SUMMARY.md.
 */

import { writeFile, mkdir } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import type { MigrationDirection, Orphan } from './types.js';

export interface EmitReportInput {
  cwd: string;
  direction: MigrationDirection;
  orphans: readonly Orphan[];
  filesScanned: number;
  filesChanged: number;
}

/**
 * Write `.planning/intel/06-migration-report.md` and return its absolute path.
 * Creates the parent dir if missing.
 */
export async function emitReport(input: EmitReportInput): Promise<string> {
  const reportPath = join(input.cwd, '.planning', 'intel', '06-migration-report.md');

  const ancestor = input.orphans.filter((o) => o.kind === 'ancestor');
  const unresolvable = input.orphans.filter((o) => o.kind === 'unresolvable');

  const lines: string[] = [];
  lines.push('# Phase 6 Migration Report');
  lines.push('');
  lines.push(`**Direction:** \`${input.direction}\``);
  lines.push(`**Files scanned:** ${input.filesScanned}`);
  lines.push(`**Files changed:** ${input.filesChanged}`);
  lines.push(
    `**Orphans:** ${input.orphans.length} (${ancestor.length} ancestor-resolved; ${unresolvable.length} unresolvable)`,
  );
  lines.push('');
  lines.push('## Ancestor-resolved orphans');
  lines.push('');
  lines.push('| file | offset | original | resolved-ancestor | direct-children of ancestor |');
  lines.push('|------|--------|----------|-------------------|-----------------------------|');
  if (ancestor.length === 0) {
    lines.push('| _(none)_ | | | | |');
  } else {
    for (const o of ancestor) {
      const rel = relativizeUnderCwd(o.filePath, input.cwd);
      const kids =
        (o.childrenInTarget ?? []).length > 0
          ? (o.childrenInTarget as string[]).join(', ')
          : input.direction === 'jj→git'
            ? '_(none / target=git)_'
            : '_(none)_';
      lines.push(
        `| ${rel} | ${o.offset} | \`${o.original}\` | \`${o.resolved ?? ''}\` | ${kids} |`,
      );
    }
  }
  lines.push('');
  lines.push('## Unresolvable orphans');
  lines.push('');
  lines.push('| file | offset | original |');
  lines.push('|------|--------|----------|');
  if (unresolvable.length === 0) {
    lines.push('| _(none)_ | | |');
  } else {
    for (const o of unresolvable) {
      const rel = relativizeUnderCwd(o.filePath, input.cwd);
      lines.push(`| ${rel} | ${o.offset} | \`${o.original}\` |`);
    }
  }
  lines.push('');
  lines.push('---');
  lines.push(
    '*Generated by gsd-migrate-vcs (Phase 6 plan 06-02). Edit inline corrections per CONTEXT D-01.*',
  );
  lines.push('');

  // Ensure .planning/intel/ exists (the report is the FIRST writer to that
  // dir in a greenfield workspace — but in this repo it's pre-existing).
  await mkdir(dirname(reportPath), { recursive: true });
  await writeFile(reportPath, lines.join('\n'), 'utf-8');
  return reportPath;
}

/**
 * Render `abs` as a path relative to `cwd` (POSIX form). Falls back to the
 * absolute path if `abs` is outside `cwd` (defensive — should not happen
 * since walk.ts only enumerates under `cwd`).
 */
function relativizeUnderCwd(abs: string, cwd: string): string {
  const cwdWithSep = cwd.endsWith('/') ? cwd : cwd + '/';
  if (abs === cwd) return '.';
  if (abs.startsWith(cwdWithSep)) {
    return abs.slice(cwdWithSep.length);
  }
  return abs;
}
